In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [37]:
import pandas as pd

df = pd.read_csv('titanic_data_updated.csv')

print(f"Dataset Shape--> \n{df.shape}")
print("-" * 50)

print(f"\nFirst 10 Rows-->")
display(df.head(10))
print("-" * 50)

print(f"\n5 Random Samples-->")
display(df.sample(5))

Dataset Shape-->
(891, 12)
--------------------------------------------------

First 10 Rows-->

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,no,third,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,no,first,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,no,third,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,yes,third,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,yes,second,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

--------------------------------------------------

5 Random Samples-->

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
212,213,no,third,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S
372,373,no,third,"Beavan, Mr. William Thomas",male,19.0,0,0,323951,8.0500,NaN,S
54,55,no,first,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
557,558,no,first,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
768,769,no,third,"Moran, Mr. Daniel J",male,NaN,1,0,371110,24.1500,NaN,Q

In [38]:
from sklearn.model_selection import train_test_split

df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train--> {X_train.shape}")
print(f"Shape of X_test--> {X_test.shape}\n")

print(f"Shape of y_train--> {y_train.shape}")
print(f"Shape of y_test--> {y_test.shape}")

Shape of X_train--> (712, 8)
Shape of X_test--> (179, 8)

Shape of y_train--> (712,)
Shape of y_test--> (179,)

In [39]:
import numpy as np
from sklearn.impute import SimpleImputer



age_imputer = SimpleImputer(missing_values=np.nan,
                            strategy='mean')
age_imputer.fit(X_train[['Age']])
X_train['Age'] = age_imputer.transform(X_train[['Age']]).ravel()
X_test['Age'] = age_imputer.transform(X_test[['Age']]).ravel()



embar_imputer = SimpleImputer(missing_values=np.nan,
                              strategy='most_frequent')
embar_imputer.fit(X_train[['Embarked']])
X_train['Embarked'] = embar_imputer.transform(X_train[['Embarked']]).ravel()
X_test['Embarked'] = embar_imputer.transform(X_test[['Embarked']]).ravel()



cabin_imputer = SimpleImputer(missing_values=np.nan,
                               strategy='constant',
                               fill_value='Missing')
cabin_imputer.fit(X_train[['Cabin']])
X_train['Cabin'] = cabin_imputer.transform(X_train[['Cabin']]).ravel()
X_test['Cabin'] = cabin_imputer.transform(X_test[['Cabin']]).ravel()

print(f"Checking X_train Missing Values-->")
display(X_train.isnull().sum())
print("-" * 40)

print(f"\nChecking X_test Missing Values-->")
display(X_test.isnull().sum())

Checking X_train Missing Values-->

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       0
Embarked    0
dtype: int64

----------------------------------------

Checking X_test Missing Values-->

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       0
Embarked    0
dtype: int64

# Outlier Detection

### Using Z-Score

In [40]:
mean_of_age = X_train['Age'].mean()
std_of_age = X_train['Age'].std()

X_train['Zscore_age'] = (X_train['Age'] - mean_of_age) / std_of_age

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age
331,first,male,45.500000,0,0,28.5000,C124,S,1.231398e+00
733,second,male,23.000000,0,0,13.0000,Missing,S,-5.001304e-01
382,third,male,32.000000,0,0,7.9250,Missing,S,1.924808e-01
704,third,male,26.000000,1,0,7.8542,Missing,S,-2.692600e-01
813,third,female,6.000000,4,2,31.2750,Missing,S,-1.808396e+00
...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,-6.540440e-01
270,first,male,29.498846,0,0,31.0000,Missing,S,2.734055e-16
860,third,male,41.000000,2,0,14.1083,Missing,S,8.850920e-01
435,first,female,14.000000,1,2,120.0000,B96 B98,S,-1.192742e+00
102,first,male,21.000000,0,1,77.2875,D26,S,-6.540440e-01

In [41]:
outliers_age = X_train[abs(X_train['Zscore_age']) > 3]

print(len(outliers_age))

display(outliers_age)

5

     Pclass   Sex   Age  SibSp  Parch    Fare    Cabin Embarked  Zscore_age
116   third  male  70.5      0      0   7.750  Missing        Q    3.155317
745   first  male  70.0      1      1  71.000      B22        S    3.116839
630   first  male  80.0      0      0  30.000      A23        S    3.886407
851   third  male  74.0      0      0   7.775  Missing        S    3.424666
672  second  male  70.0      0      0  10.500  Missing        S    3.116839

In [42]:
mean_of_fare = X_train['Fare'].mean()
std_of_fare = X_train['Fare'].std()

X_train['Zscore_fare'] = (X_train['Fare'] - mean_of_fare) / std_of_fare

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age,Zscore_fare
331,first,male,45.500000,0,0,28.5000,C124,S,1.231398e+00,-0.078628
733,second,male,23.000000,0,0,13.0000,Missing,S,-5.001304e-01,-0.376880
382,third,male,32.000000,0,0,7.9250,Missing,S,1.924808e-01,-0.474533
704,third,male,26.000000,1,0,7.8542,Missing,S,-2.692600e-01,-0.475896
813,third,female,6.000000,4,2,31.2750,Missing,S,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,-6.540440e-01,-0.479825
270,first,male,29.498846,0,0,31.0000,Missing,S,2.734055e-16,-0.030523
860,third,male,41.000000,2,0,14.1083,Missing,S,8.850920e-01,-0.355554
435,first,female,14.000000,1,2,120.0000,B96 B98,S,-1.192742e+00,1.682019
102,first,male,21.000000,0,1,77.2875,D26,S,-6.540440e-01,0.860143

In [43]:
outliers_fare = X_train[abs(X_train['Zscore_fare']) > 3]

print(len(outliers_fare))

display(outliers_fare)

17

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age,Zscore_fare
118,first,male,24.000000,0,1,247.5208,B58 B60,C,-4.231736e-01,4.135780
716,first,female,38.000000,0,0,227.5250,C45,C,6.542216e-01,3.751020
377,first,male,27.000000,0,2,211.5000,C82,C,-1.923032e-01,3.442666
742,first,female,21.000000,2,2,262.3750,B57 B59 B63 B66,C,-6.540440e-01,4.421605
380,first,female,42.000000,0,0,227.5250,Missing,C,9.620488e-01,3.751020
779,first,female,43.000000,0,1,211.3375,B3,S,1.039006e+00,3.439539
730,first,female,29.000000,0,0,211.3375,B5,S,-3.838960e-02,3.439539
88,first,female,23.000000,3,2,263.0000,C23 C25 C27,S,-5.001304e-01,4.433631
341,first,female,24.000000,3,2,263.0000,C23 C25 C27,S,-4.231736e-01,4.433631
557,first,male,29.498846,0,0,227.5250,Missing,C,2.734055e-16,3.751020
737,first,male,35.000000,0,0,512.3292,B101,C,4.233512e-01,9.231235
679,first,male,36.000000,0,1,512.3292,B51 B53 B55,C,5.003080e-01,9.231235
438,first,male,64.000000,1,4,263.0000,C23 C25 C27,S,2.655098e+00,4.433631
689,first,female,15.000000,0,1,211.3375,B5,S,-1.115785e+00,3.439539
258,first,female,35.000000,0,0,512.3292,Missing,C,4.233512e-01,9.231235
27,first,male,19.000000,3,2,263.0000,C23 C25 C27,S,-8.079576e-01,4.433631
700,first,female,18.000000,1,0,227.5250,C62 C64,C,-8.849144e-01,3.751020

### Using IQR

In [44]:
age_Q1 = X_train['Age'].quantile(0.25)
age_Q3 = X_train['Age'].quantile(0.75)

age_IQR = age_Q3 - age_Q1

age_min = age_Q1 - 1.5 * age_IQR
age_max = age_Q3 + 1.5 * age_IQR

print(age_min, age_max)

2.5 54.5

In [45]:
age_outliers = X_train[(X_train['Age'] < age_min) | (X_train['Age'] > age_max)]

print(len(age_outliers))
display(age_outliers)

54

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age,Zscore_fare
326,third,male,61.00,0,0,6.2375,Missing,S,2.424228,-0.507004
483,third,female,63.00,0,0,9.5875,Missing,S,2.578141,-0.442543
7,third,male,2.00,3,1,21.0750,Missing,S,-2.116223,-0.221500
305,first,male,0.92,1,2,151.5500,C22 C26,S,-2.199336,2.289105
829,first,female,62.00,0,0,80.0000,B28,S,2.501185,0.912337
626,second,male,57.00,0,0,12.3500,Missing,Q,2.116401,-0.389387
456,first,male,65.00,0,0,26.5500,E38,S,2.732055,-0.116150
172,third,female,1.00,1,1,11.1333,Missing,S,-2.193180,-0.412799
164,third,male,1.00,4,1,39.6875,Missing,S,-2.193180,0.136642
381,third,female,1.00,0,2,15.7417,Missing,C,-2.193180,-0.324124
694,first,male,60.00,0,0,26.5500,Missing,S,2.347271,-0.116150
587,first,male,60.00,1,1,79.2000,B41,C,2.347271,0.896943
570,second,male,62.00,0,0,10.5000,Missing,S,2.501185,-0.424985
879,first,female,56.00,0,1,83.1583,C50,C,2.039444,0.973109
94,third,male,59.00,0,0,7.2500,Missing,S,2.270314,-0.487522
11,first,female,58.00,0,0,26.5500,C103,S,2.193357,-0.116150
644,third,female,0.75,2,1,19.2583,Missing,C,-2.212419,-0.256458
15,second,female,55.00,0,0,16.0000,Missing,S,1.962487,-0.319154
530,second,female,2.00,1,1,26.0000,Missing,S,-2.116223,-0.126733
340,second,male,2.00,1,1,26.0000,F2,S,-2.116223,-0.126733
487,first,male,58.00,0,0,29.7000,B37,C,2.193357,-0.055538
467,first,male,56.00,0,0,26.5500,Missing,S,2.039444,-0.116150
827,second,male,1.00,0,2,37.0042,Missing,C,-2.193180,0.085010
116,third,male,70.50,0,0,7.7500,Missing,Q,3.155317,-0.477901
745,first,male,70.00,1,1,71.0000,B22,S,3.116839,0.739159
268,first,female,58.00,0,1,153.4625,C125,S,2.193357,2.325906
479,third,female,2.00,0,1,12.2875,Missing,S,-2.116223,-0.390590
195,first,female,58.00,0,0,146.5208,B80,C,2.193357,2.192333
16,third,male,2.00,4,1,29.1250,Missing,Q,-2.116223,-0.066602
469,third,female,0.75,2,1,19.2583,Missing,C,-2.212419,-0.256458
630,first,male,80.00,0,0,30.0000,A23,S,3.886407,-0.049765
152,third,male,55.50,0,0,8.0500,Missing,S,2.000966,-0.472128
684,second,male,60.00,1,1,39.0000,Missing,S,2.347271,0.123413
119,third,female,2.00,4,2,31.2750,Missing,S,-2.116223,-0.025232
297,first,female,2.00,1,2,151.5500,C22 C26,S,-2.116223,2.289105
851,third,male,74.00,0,0,7.7750,Missing,S,3.424666,-0.477420
183,second,male,1.00,2,1,39.0000,F4,S,-2.193180,0.123413
438,first,male,64.00,1,4,263.0000,C23 C25 C27,S,2.655098,4.433631
788,third,male,1.00,1,2,20.5750,Missing,S,-2.193180,-0.231122
672,second,male,70.00,0,0,10.5000,Missing,S,3.116839,-0.424985
386,third,male,1.00,5,2,46.9000,Missing,S,-2.193180,0.275425
232,second,male,59.00,0,0,13.5000,Missing,S,2.270314,-0.367259
824,third,male,2.00,4,1,39.6875,Missing,S,-2.116223,0.136642
803,third,male,0.42,0,1,8.5167,Missing,C,-2.237815,-0.463148
170,first,male,61.00,0,0,33.5000,B19,S,2.424228,0.017582
755,second,male,0.67,1,1,14.5000,Missing,S,-2.218576,-0.348017
642,third,female,2.00,3,2,27.9000,Missing,S,-2.116223,-0.090174
647,first,male,56.00,0,0,35.5000,A26,C,2.039444,0.056066
492,first,male,55.00,0,0,30.5000,C30,S,1.962487,-0.040144
555,first,male,62.00,0,0,26.5500,Missing,S,2.501185,-0.116150
205,third,female,2.00,0,1,10.4625,G6,S,-2.116223,-0.425707
366,first,female,60.00,1,0,75.2500,D37,C,2.347271,0.820937
831,second,male,0.83,1,1,18.7500,Missing,S,-2.206263,-0.266238
252,first,male,62.00,0,0,26.5500,C87,S,2.501185,-0.116150

In [46]:
fare_Q1 = X_train['Fare'].quantile(0.25)
fare_Q3 = X_train['Fare'].quantile(0.75)

fare_IQR = fare_Q3 - fare_Q1

fare_min = max(0, fare_Q1 - 1.5 * fare_IQR)
fare_max = fare_Q3 + 1.5 * fare_IQR

print(fare_min, fare_max)

0 64.3625

In [47]:
fare_outliers = X_train[(X_train['Fare'] < fare_min) | (X_train['Fare'] > fare_max)]

print(len(fare_outliers))
display(fare_outliers)

96

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age,Zscore_fare
118,first,male,24.0,0,1,247.5208,B58 B60,C,-0.423174,4.135780
486,first,female,35.0,1,0,90.0000,C93,S,0.423351,1.104757
716,first,female,38.0,0,0,227.5250,C45,C,0.654222,3.751020
390,first,male,36.0,1,2,120.0000,B96 B98,S,0.500308,1.682019
377,first,male,27.0,0,2,211.5000,C82,C,-0.192303,3.442666
...,...,...,...,...,...,...,...,...,...,...
681,first,male,27.0,0,0,76.7292,D49,C,-0.192303,0.849400
385,second,male,18.0,0,0,73.5000,Missing,S,-0.884914,0.787264
700,first,female,18.0,1,0,227.5250,C62 C64,C,-0.884914,3.751020
435,first,female,14.0,1,2,120.0000,B96 B98,S,-1.192742,1.682019
102,first,male,21.0,0,1,77.2875,D26,S,-0.654044,0.860143

# Best detector of Outlier and Handling

In [48]:
# Z-Score outlier detection is better for age ouliers

X_train = X_train[abs(X_train['Zscore_age']) <= 3]

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age,Zscore_fare
331,first,male,45.500000,0,0,28.5000,C124,S,1.231398e+00,-0.078628
733,second,male,23.000000,0,0,13.0000,Missing,S,-5.001304e-01,-0.376880
382,third,male,32.000000,0,0,7.9250,Missing,S,1.924808e-01,-0.474533
704,third,male,26.000000,1,0,7.8542,Missing,S,-2.692600e-01,-0.475896
813,third,female,6.000000,4,2,31.2750,Missing,S,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,-6.540440e-01,-0.479825
270,first,male,29.498846,0,0,31.0000,Missing,S,2.734055e-16,-0.030523
860,third,male,41.000000,2,0,14.1083,Missing,S,8.850920e-01,-0.355554
435,first,female,14.000000,1,2,120.0000,B96 B98,S,-1.192742e+00,1.682019
102,first,male,21.000000,0,1,77.2875,D26,S,-6.540440e-01,0.860143

In [49]:
X_train['Fare'] = X_train['Fare'].clip(fare_min, fare_max)

X_train['Fare'].max()

C:\Users\User\AppData\Local\Temp\ipykernel_1684\3237031298.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare'] = X_train['Fare'].clip(fare_min, fare_max)

64.3625

# Encoading

In [50]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Zscore_age,Zscore_fare
331,first,male,45.500000,0,0,28.5000,C124,S,1.231398e+00,-0.078628
733,second,male,23.000000,0,0,13.0000,Missing,S,-5.001304e-01,-0.376880
382,third,male,32.000000,0,0,7.9250,Missing,S,1.924808e-01,-0.474533
704,third,male,26.000000,1,0,7.8542,Missing,S,-2.692600e-01,-0.475896
813,third,female,6.000000,4,2,31.2750,Missing,S,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,-6.540440e-01,-0.479825
270,first,male,29.498846,0,0,31.0000,Missing,S,2.734055e-16,-0.030523
860,third,male,41.000000,2,0,14.1083,Missing,S,8.850920e-01,-0.355554
435,first,female,14.000000,1,2,64.3625,B96 B98,S,-1.192742e+00,1.682019
102,first,male,21.000000,0,1,64.3625,D26,S,-6.540440e-01,0.860143

In [51]:
X_train.drop(['Zscore_age', 'Zscore_fare'], axis=1, inplace=True, errors='ignore')

X_train

C:\Users\User\AppData\Local\Temp\ipykernel_1684\2777992828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train.drop(['Zscore_age', 'Zscore_fare'], axis=1, inplace=True, errors='ignore')

     Pclass     Sex        Age  SibSp  Parch     Fare    Cabin Embarked
331   first    male  45.500000      0      0  28.5000     C124        S
733  second    male  23.000000      0      0  13.0000  Missing        S
382   third    male  32.000000      0      0   7.9250  Missing        S
704   third    male  26.000000      1      0   7.8542  Missing        S
813   third  female   6.000000      4      2  31.2750  Missing        S
..      ...     ...        ...    ...    ...      ...      ...      ...
106   third  female  21.000000      0      0   7.6500  Missing        S
270   first    male  29.498846      0      0  31.0000  Missing        S
860   third    male  41.000000      2      0  14.1083  Missing        S
435   first  female  14.000000      1      2  64.3625  B96 B98        S
102   first    male  21.000000      0      1  64.3625      D26        S

[707 rows x 8 columns]

# Ordinal Value Encoding

In [52]:
from sklearn.preprocessing import OrdinalEncoder

pclass_endoder = OrdinalEncoder(categories=[['third', 'second', 'first']])

pclass_endoder.fit(X_train[['Pclass']])

X_train['Encoder_pclass'] = pclass_endoder.transform(X_train[['Pclass']]).ravel()
X_test['Encoder_pclass'] = pclass_endoder.transform(X_test[['Pclass']]).ravel()

C:\Users\User\AppData\Local\Temp\ipykernel_1684\2999657507.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Encoder_pclass'] = pclass_endoder.transform(X_train[['Pclass']]).ravel()

In [53]:
X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Encoder_pclass
331,first,male,45.500000,0,0,28.5000,C124,S,2.0
733,second,male,23.000000,0,0,13.0000,Missing,S,1.0
382,third,male,32.000000,0,0,7.9250,Missing,S,0.0
704,third,male,26.000000,1,0,7.8542,Missing,S,0.0
813,third,female,6.000000,4,2,31.2750,Missing,S,0.0
...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,0.0
270,first,male,29.498846,0,0,31.0000,Missing,S,2.0
860,third,male,41.000000,2,0,14.1083,Missing,S,0.0
435,first,female,14.000000,1,2,64.3625,B96 B98,S,2.0
102,first,male,21.000000,0,1,64.3625,D26,S,2.0

In [54]:
X_test

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Encoder_pclass
709,third,male,29.498846,1,1,15.2458,Missing,C,0.0
439,second,male,31.000000,0,0,10.5000,Missing,S,1.0
840,third,male,20.000000,0,0,7.9250,Missing,S,0.0
720,second,female,6.000000,0,1,33.0000,Missing,S,1.0
39,third,female,14.000000,1,0,11.2417,Missing,C,0.0
...,...,...,...,...,...,...,...,...,...
433,third,male,17.000000,0,0,7.1250,Missing,S,0.0
773,third,male,29.498846,0,0,7.2250,Missing,C,0.0
25,third,female,38.000000,1,5,31.3875,Missing,S,0.0
84,second,female,17.000000,0,0,10.5000,Missing,S,1.0
10,third,female,4.000000,1,1,16.7000,G6,S,0.0

# Nominal Value Encoding

### One Hot Encoding

In [55]:
from sklearn.preprocessing import OneHotEncoder

sex_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

sex_encoder.fit(X_train[['Sex']])

encoded_df = sex_encoder.transform(X_train[['Sex']])
X_train = pd.concat([X_train, encoded_df], axis=1)

encoded_df = sex_encoder.transform(X_test[['Sex']])
X_test = pd.concat([X_test, encoded_df], axis=1)

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Encoder_pclass,Sex_female,Sex_male
331,first,male,45.500000,0,0,28.5000,C124,S,2.0,0.0,1.0
733,second,male,23.000000,0,0,13.0000,Missing,S,1.0,0.0,1.0
382,third,male,32.000000,0,0,7.9250,Missing,S,0.0,0.0,1.0
704,third,male,26.000000,1,0,7.8542,Missing,S,0.0,0.0,1.0
813,third,female,6.000000,4,2,31.2750,Missing,S,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,0.0,1.0,0.0
270,first,male,29.498846,0,0,31.0000,Missing,S,2.0,0.0,1.0
860,third,male,41.000000,2,0,14.1083,Missing,S,0.0,0.0,1.0
435,first,female,14.000000,1,2,64.3625,B96 B98,S,2.0,1.0,0.0
102,first,male,21.000000,0,1,64.3625,D26,S,2.0,0.0,1.0

In [56]:
embarked_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

embarked_encoder.fit(X_train[['Embarked']])

encoded_df = embarked_encoder.transform(X_train[['Embarked']])
X_train = pd.concat([X_train, encoded_df], axis=1)

encoded_df = embarked_encoder.transform(X_test[['Embarked']])
X_test = pd.concat([X_test, encoded_df], axis=1)

X_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Encoder_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
331,first,male,45.500000,0,0,28.5000,C124,S,2.0,0.0,1.0,0.0,0.0,1.0
733,second,male,23.000000,0,0,13.0000,Missing,S,1.0,0.0,1.0,0.0,0.0,1.0
382,third,male,32.000000,0,0,7.9250,Missing,S,0.0,0.0,1.0,0.0,0.0,1.0
704,third,male,26.000000,1,0,7.8542,Missing,S,0.0,0.0,1.0,0.0,0.0,1.0
813,third,female,6.000000,4,2,31.2750,Missing,S,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,0.0,1.0,0.0,0.0,0.0,1.0
270,first,male,29.498846,0,0,31.0000,Missing,S,2.0,0.0,1.0,0.0,0.0,1.0
860,third,male,41.000000,2,0,14.1083,Missing,S,0.0,0.0,1.0,0.0,0.0,1.0
435,first,female,14.000000,1,2,64.3625,B96 B98,S,2.0,1.0,0.0,0.0,0.0,1.0
102,first,male,21.000000,0,1,64.3625,D26,S,2.0,0.0,1.0,0.0,0.0,1.0

In [57]:
X_train.drop(['Pclass', 'Sex', 'Embarked'], axis=1, inplace=True)

X_test.drop(['Pclass', 'Sex', 'Embarked'], axis=1, inplace=True)

In [58]:
X_train.sample(5)

,Age,SibSp,Parch,Fare,Cabin,Encoder_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
335,29.498846,0,0,7.8958,Missing,0.0,0.0,1.0,0.0,0.0,1.0
107,29.498846,0,0,7.7750,Missing,0.0,0.0,1.0,0.0,0.0,1.0
872,33.000000,0,0,5.0000,B51 B53 B55,2.0,0.0,1.0,0.0,0.0,1.0
844,17.000000,0,0,8.6625,Missing,0.0,0.0,1.0,0.0,0.0,1.0
618,4.000000,2,1,39.0000,F4,1.0,1.0,0.0,0.0,0.0,1.0

# Encoding the Cabin features

In [59]:
X_train['Cabin'].value_counts()

Cabin
Missing        550
C23 C25 C27      4
F2               3
E101             3
B96 B98          3
              ...
C104             1
D11              1
C7               1
C86              1
C62 C64          1
Name: count, Length: 117, dtype: int64

In [60]:
X_train['Cabin_deck'] = X_train['Cabin'].astype(str).str[0]
X_test['Cabin_deck'] = X_test['Cabin'].astype(str).str[0]

X_train

,Age,SibSp,Parch,Fare,Cabin,Encoder_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Cabin_deck
331,45.500000,0,0,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,C
733,23.000000,0,0,13.0000,Missing,1.0,0.0,1.0,0.0,0.0,1.0,M
382,32.000000,0,0,7.9250,Missing,0.0,0.0,1.0,0.0,0.0,1.0,M
704,26.000000,1,0,7.8542,Missing,0.0,0.0,1.0,0.0,0.0,1.0,M
813,6.000000,4,2,31.2750,Missing,0.0,1.0,0.0,0.0,0.0,1.0,M
...,...,...,...,...,...,...,...,...,...,...,...,...
106,21.000000,0,0,7.6500,Missing,0.0,1.0,0.0,0.0,0.0,1.0,M
270,29.498846,0,0,31.0000,Missing,2.0,0.0,1.0,0.0,0.0,1.0,M
860,41.000000,2,0,14.1083,Missing,0.0,0.0,1.0,0.0,0.0,1.0,M
435,14.000000,1,2,64.3625,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,B
102,21.000000,0,1,64.3625,D26,2.0,0.0,1.0,0.0,0.0,1.0,D

In [61]:
X_train['Cabin_deck'].value_counts()

Cabin_deck
M    550
C     52
B     37
E     24
D     19
F     12
A      9
G      3
T      1
Name: count, dtype: int64

In [62]:
deck_encoder = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')

deck_encoder.fit(X_train[['Cabin_deck']])

encoded_df = deck_encoder.transform(X_train[['Cabin_deck']])
X_train = pd.concat([X_train, encoded_df], axis=1)

encoded_df = deck_encoder.transform(X_test[['Cabin_deck']])
X_test = pd.concat([X_test, encoded_df], axis=1)

X_train

,Age,SibSp,Parch,Fare,Cabin,Encoder_pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Cabin_deck,Cabin_deck_B,Cabin_deck_C,Cabin_deck_D,Cabin_deck_E,Cabin_deck_F,Cabin_deck_G,Cabin_deck_M,Cabin_deck_T
331,45.500000,0,0,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,C,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,23.000000,0,0,13.0000,Missing,1.0,0.0,1.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
382,32.000000,0,0,7.9250,Missing,0.0,0.0,1.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
704,26.000000,1,0,7.8542,Missing,0.0,0.0,1.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
813,6.000000,4,2,31.2750,Missing,0.0,1.0,0.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,21.000000,0,0,7.6500,Missing,0.0,1.0,0.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
270,29.498846,0,0,31.0000,Missing,2.0,0.0,1.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
860,41.000000,2,0,14.1083,Missing,0.0,0.0,1.0,0.0,0.0,1.0,M,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
435,14.000000,1,2,64.3625,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,B,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,21.000000,0,1,64.3625,D26,2.0,0.0,1.0,0.0,0.0,1.0,D,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [63]:
X_train.drop(['Cabin_deck'], axis=1, inplace=True)
X_test.drop(['Cabin_deck'], axis=1, inplace=True)

# Level Encoding

In [64]:
y_train

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

In [65]:
# lebel encoding only for target column
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()

lbl.fit(y_train)
y_train_array = lbl.transform(y_train)
y_test_array = lbl.transform(y_test)

In [66]:
y_train_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0])

In [67]:
y_train = pd.Series(y_train_array, index= y_train.index, name = y_train.name)
y_test = pd.Series(y_test_array, index= y_test.index, name = y_test.name)

In [68]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64